USE [master]
GO

/****** Object:  Database [Foursquare]    Script Date: 26/05/2022 00:32:44 ******/
CREATE DATABASE [Foursquare]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Foursquare', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Foursquare.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Foursquare_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Foursquare_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Foursquare] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Foursquare].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Foursquare] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Foursquare] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Foursquare] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Foursquare] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Foursquare] SET ARITHABORT OFF 
GO

ALTER DATABASE [Foursquare] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Foursquare] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Foursquare] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Foursquare] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Foursquare] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Foursquare] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Foursquare] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Foursquare] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Foursquare] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Foursquare] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Foursquare] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Foursquare] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Foursquare] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Foursquare] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Foursquare] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Foursquare] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Foursquare] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Foursquare] SET RECOVERY FULL 
GO

ALTER DATABASE [Foursquare] SET  MULTI_USER 
GO

ALTER DATABASE [Foursquare] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Foursquare] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Foursquare] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Foursquare] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Foursquare] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Foursquare] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Foursquare] SET  READ_WRITE 
GO


